plugins {
    id 'com.android.application'
}

android {
    namespace 'com.apollo.avairbridge'
    compileSdk 35

    signingConfigs {
        prototype {
            storeFile file('../ava-ir-bridge.keystore')
            storePassword 'apolloirbridge'
            keyAlias 'avairbridge'
            keyPassword 'apolloirbridge'
        }
    }

    defaultConfig {
        applicationId 'com.apollo.avairbridge'
        minSdk 23
        targetSdk 30
        versionCode 11
        versionName '0.9.2'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.prototype
        }
    }
}
